#!/bin/bash

if [ -n "$1" ]; then
	###################################################
	###################   Config   ####################
	###################################################
	
	#Leave variables blank if not in use
	
	#the directory that wordpress will be installed to 
	project_directory='/Users/Brent/Files/Sites/Projects/vhosts'

	#the svn location of the starter theme to check into the new install (leave blank if you have no starter theme)
	svn_starter_theme="file:///Users/Brent/Files/Sites/svn/lib/PHP/wordpress/themes/puddlejumper/trunk"
	
	#The location of your svn repository for checking in projects (aka where the project theme gets checked into)
	svn_project_directory="file:///Users/Brent/Files/Sites/svn/web"
	
	#local mysql settings
	mysql_bin="/Applications/MAMP/Library/bin/mysql"
	mysql_user="####"
	mysql_pass="####"
	
	###################################################
	################### / Config   ####################
	###################################################
	
	#Set the db and domain vars
	
	#make the name of the domain/ project directory and the 
	#name of the database/theme (these don't have the domain extension)
	#so entering puddletowndesign.com will do the following
	#  - name the project directory and svn repo puddletowndesign.com
	#  - name the database and the theme puddletowndesign
	domain=$1
	db="${domain%.*}"
	
	
	###################################################
	################### / Testing  ####################
	###################################################
	
	
	#Import predefined database
	
	#copy database to temp
	
	#edit database file
	
	#import it into mysql
	
	##edit the /etc/hosts
	#echo "Making a new virtual host - Writing to /etc/hosts"
	#echo "127.0.0.1 $1" >> /etc/hosts
	
	#make a new vitual host
	#/Applications/MAMP/Library/bin/apachectl restart
	
	
	#exit

	################################################
	# 1. move to project directory (set directory to use here)
	################################################
	echo "Setting install location to $project_directory/"
	cd $project_directory/
	
	################################################
	# 2. download a copy of wordpress to the vhosts directory
	################################################
	echo "Downloading a copy of wordpress trunk"
	svn export http://core.svn.wordpress.org/trunk $domain
	echo "Wordpress Download Complete"
	
    
	################################################
	# 3. Copy the wp-config-sample.php and rename it wp-config.php
	################################################
	echo "Making a new config file"
	cp $domain/wp-config-sample.php $domain/wp-config.php
	
	################################################
	# 4. edit the wordpress config file to the defined varibles above
	################################################
	sed -i '' "s/database_name_here/$db/g" $domain/wp-config.php
	sed -i '' "s/username_here/$mysql_user/g" $domain/wp-config.php
	sed -i '' "s/password_here/$mysql_pass/g" $domain/wp-config.php
	
	
	################################################
	# 5. move the current directory to the theme directory of the new wordpress install
	################################################
	cd $domain/wp-content/themes/
	
	
	####################################################################
	# Exports a copy of the starter theme from svn and then imports it
	# back into it's own svn repo directory named afer the domain name
	####################################################################
	echo "Exporting a copy of the Puddlejumper WP theme to the new install"
	mkdir temp
	mkdir temp/$domain
	mkdir temp/$domain/tags
	mkdir temp/$domain/branches
	svn export $svn_starter_theme temp/$domain/trunk
	
	#Import the installed theme into SVN as Site name entered
	echo "Importing The newly installed theme into SVN as $domain"
	svn import temp/$domain $svn_project_directory/$domain -m "$domain First Import"
    
	#check out a new working copy of the site's starter theme
	echo "checking out the a new working copy"
	svn checkout $svn_project_directory/$domain/trunk $db
    
	#delete the temp directory
	echo "cleaning up the temp directory..."
	rm -r temp
    
    
    
	################################################
	# Creates a new database
	################################################
	if [ -n "$mysql_user" ]; then
		#Create a new mysql database
		echo "Creating $db database..."
		$mysql_bin -u$mysql_user -p$mysql_pass -e "CREATE DATABASE IF NOT EXISTS $db;"
		echo "$db MYSQL database created..."
	fi
    
    
	#######################################################################
	####################### Interface Actions :) ##########################
	#######################################################################
	
	#opens the entire development environment when complete
	open /Applications/MAMP\ PRO/MAMP\ PRO.app
	open /Applications/Cornerstone.app
	open /Applications/MAMP/logs/php_error.log
	
	echo "opening in finder..."
	open $project_directory/$domain
    
	echo "opening $domain wp-theme in textmate..."
	mate $project_directory/$domain/wp-content/themes/$db
    
	echo "opening http://$domain in browser"
	open "http://$domain/"
    
	echo "[Process Complete!]"
   
	exit	

else
	echo "enter the name of the domain name for the new wordpress site"
	echo ""
	echo "a new directory and virtual host in the vhosts/directory will be created and a new database will be installed locally"
	echo ""
	read project_name
	exit;
fi